### ISSUE TITLE
navbar collapses on mobile, does not reopen.

### ISSUE THREAD

**Issue by sheenobu** [sockethub/website-sockethub.org#4]
sockethub.org collapses the side menu and does not allow opening it (since sockethub.org includes no javascript). This happens on mobile browsers or anytime a browser gets to a certain size (emulating a mobile browser).

Potential fixes:

 * Include bootstrap javascript
 * Get rid of "navbar-collapse"/"collapse" CSS classes in navbar.
 * ???

![sockethub-bug](https://cloud.githubusercontent.com/assets/1443459/7904415/7f26e87a-07c7-11e5-8ba8-874d18004236.png)

**Comment by silverbucket** [comment]
Thanks for pointing this out @sheenobu, just fixed it by adding the bootstrap (and jquery) js files.
