### ISSUE TITLE
Fix RSS feed with URL link

### ISSUE THREAD

**Issue by raucao** [sockethub/website-sockethub.org#5]
I only accidentally stumbled upon the latest news entry. Would be nice to have an RSS or ATOM feed for those, so one can subscribe to news (and we can also have hal8000 post them to the #sockethub IRC that way).

**Comment by silverbucket** [comment]
There is a feed at http://sockethub.org/feed.xml can we add it to hal8000?

**Comment by silverbucket** [comment]
oops didn't mean to close

**Comment by skddc** [comment]
> There is a feed at http://sockethub.org/feed.xml can we add it to hal8000?

Done.

**Comment by skddc** [comment]
Re-opening, so we can fix the missing link. If it's not possible to link to single items, we can just link all of them to the home page for example/
